# The Default RetinaNet based experiments
vanilla:
  name: "vanilla"
  model: "VanillaRetinaNet"
  datamodule: "TableDatasetModule"
  learning_rate: 1e-5
  batch_size: 2
  train_eval_split: 0.8

# The RetinaNet V2 based experiments
vanilla_v2:
  name: "vanilla_v2"
  model: "VanillaRetinaNetV2"
  datamodule: "TableDatasetModule"
  learning_rate: 1e-5
  batch_size: 2
  train_eval_split: 0.8

vanilla_v2_2:
  name: "vanilla_v2_2"
  model: "VanillaRetinaNetV2"
  datamodule: "TableDatasetModule"
  learning_rate: 1e-4
  batch_size: 2
  train_eval_split: 0.8

vanilla_v2_3:
  name: "vanilla_v2_3"
  model: "VanillaRetinaNetV2"
  datamodule: "TableDatasetModule"
  learning_rate: 1e-6
  batch_size: 2
  train_eval_split: 0.8

vanilla_v2_4:
  name: "vanilla_v2_4"
  model: "VanillaRetinaNetV2"
  datamodule: "TableDatasetModule"
  learning_rate: 1e-3
  batch_size: 2
  train_eval_split: 0.8

vanilla_v2_5:
  name: "vanilla_v2_5"
  model: "VanillaRetinaNetV2"
  datamodule: "TableDatasetModule"
  learning_rate: 1e-5
  batch_size: 4
  train_eval_split: 0.8


# RetinaNet based on ResNet18 based experiments
retinanet_resnet18_fpn:
  name: "retinanet_resnet18_fpn"
  model: "RetinaNetResnet18FPN"
  datamodule: "TableDatasetModule"
  learning_rate: 1e-5
  batch_size: 2
  train_eval_split: 0.8