wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train/step/total_loss
      5: 1
      6:
      - 1
    - 1: train/step/classification_loss
      5: 1
      6:
      - 1
    - 1: train/step/regression_loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    python_version: 3.7.13
    start_time: 1666608689.787723
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      2:
      - 1
      - 9
      - 41
      - 55
      3:
      - 7
      - 15
      - 23
      4: 3.7.13
      5: 0.13.3
      8:
      - 5
batch_size:
  desc: null
  value: 2
lr:
  desc: null
  value: 1.0e-05
num_classes:
  desc: null
  value: 2
pretrained:
  desc: null
  value: true
