site_name: Table Detection using Pytorch and Lightning

theme:
  name: material
  palette:
    primary: teal
    accent: deep orange
  features:
    - navigation.tabs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Guides:
    - Training: guides/train.md
    - Utilities:
      - Extract Labelled: guides/utils/extract-labelled.md
