site_name: Table Detection using Pytorch and Lightning

theme:
  name: material
  palette:
    primary: teal
    accent: deep orange
  features:
    - navigation.tabs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  
  - Tools:
  
    - Overview: tools/index.md
  
    - Utilities:
      - Overview: tools/utils/index.md
      - Data House Keeper: tools/utils/data-house-keeper.md
      - PascalVOC to CSV: tools/utils/pascalvoc-to-csv.md
      - PDF Deduplication: tools/utils/pdf-dedup.md
  
    - Network:
      - Overview: tools/network/index.md
      - Visualise: tools/network/visualise.md
      - Infer: tools/network/infer.md
      - Train: tools/network/train.md
      - Extract Tables: tools/network/extract-tables.md
      - Evaluate: tools/network/evaluate.md
  
  - Guides:
    - Overview: guides/index.md
    - Reproduce Evaluation:
      - Overview: guides/evaluation/index.md
      - Setup: guides/evaluation/setup.md
      - Reproduce: guides/evaluation/reproduce.md
    - Train Models:
      - Overview: guides/training/index.md
      - About Datasets: guides/training/dataset.md
      - Checkpoints: guides/training/checkpoints.md
      - Metrics: guides/training/metrics.md
      - Experiment Configurations: guides/training/configs.md
      - Training Command: guides/training/command.md

  - Downloads:
    - Overview: downloads/index.md
